# Generated by Django 3.0.8 on 2020-07-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoPoblacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de creación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha hora en que se creó el objeto.', verbose_name='Fecha de creacion')),
                ('ip_modificacion', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modificación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='Fecha de Modificación')),
                ('num_documento', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Número de cédula')),
                ('nombres', models.CharField(db_index=True, max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Apellidos')),
                ('sexo', models.CharField(blank=True, choices=[('H', 'HOMBRE'), ('M', 'MUJER')], max_length=1, null=True, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=10, verbose_name='# Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('edad', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('descripcion_fisica', models.TextField(max_length=250, verbose_name='Descripción fisica')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personas/fotos', verbose_name='Foto')),
                ('tiene_hijos', models.BooleanField(default=False, verbose_name='Tiene hijos?')),
                ('puntaje_sisben', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Puntaje Sisben')),
                ('etnia', models.CharField(blank=True, help_text='De acuerdo a sus rasgos fisicos y culturales.', max_length=1, null=True, verbose_name='Etnia')),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beneficios.Barrio', verbose_name='Barrio')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beneficios.Comuna', verbose_name='Comuna')),
                ('grupos_poblacionales', models.ManyToManyField(related_name='personas', to='beneficios.GrupoPoblacional', verbose_name='Grupos poblacionales')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='beneficios.TipoDocumento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ('num_documento',),
                'get_latest_by': 'fecha_creacion',
            },
        ),
        migrations.AddField(
            model_name='barrio',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficios.Comuna'),
        ),
    ]
