# Generated by Django 3.0.8 on 2020-07-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_auto_20200713_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='grupos_poblacionales',
            field=models.ManyToManyField(blank=True, null=True, related_name='personas', to='beneficios.GrupoPoblacional', verbose_name='Grupos poblacionales'),
        ),
    ]
