# Generated by Django 3.0.8 on 2020-07-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0003_auto_20200713_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='etnia',
            field=models.CharField(blank=True, choices=[('AFRO', 'Afro'), ('INDIGENA', 'Indigena'), ('MESTIZO', 'Mestizo'), ('NINGUNA', 'Ninguna')], help_text='De acuerdo a sus rasgos fisicos y culturales.', max_length=15, null=True, verbose_name='Etnia'),
        ),
    ]
