# Generated by Django 3.0.8 on 2020-07-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0004_auto_20200713_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='beneficios.Municipio'),
            preserve_default=False,
        ),
    ]
