# Generated by Django 3.0.8 on 2020-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0005_auto_20200713_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código autogenerado'),
        ),
    ]
