# Generated by Django 3.0.8 on 2020-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0006_persona_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código autogenerado'),
        ),
    ]
