# Generated by Django 3.0.8 on 2020-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0007_auto_20200714_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Está activo?'),
        ),
    ]
